//Fireball constants
const FIREBALL_START_FIRE_RATE = 1;
const FIREBALL_VELOCITY = 0;

//Score constants
const SCORE_MAXIMUM = 999999;
const SCORE_INCREMENT_FIREBALL = 10;
const SCORE_INCREMENT_FIRESTREAM = 50;